
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'build date'
        required: true
        default: '2020-0929'

env:
  HOST: i686-w64-mingw32
  DEP_INSTALL_SH: install_deps.sh

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install 
      run: |
        sudo cp sources.list /etc/apt/sources.list
        sudo apt -qq update
        sudo apt-get install -y -qq make binutils autoconf automake \
        autotools-dev libtool pkg-config git curl dpkg-dev gcc-mingw-w64 \
        g++-mingw-w64 autopoint libcppunit-dev libxml2-dev libgcrypt11-dev lzip

    - name: Compile deps
      run: |
        pwd
        chmod +x $GITHUB_WORKSPACE/$DEP_INSTALL_SH
        sudo bash $GITHUB_WORKSPACE/$DEP_INSTALL_SH 

    - name: Compile
      run: |
        wget https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0.tar.gz
        tar xf aria2-1.35.0.tar.gz
        cd aria2-1.35.0
        autoreconf -i && ./mingw-config && make
        $HOST-strip src/aria2c.exe

    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        name: aria2-artifact
        path: src/aria2c.exe
